Repository aquality-automation/aquality-winappdriver-dotnet, pull requests merged in 2019-12, with the labels that each got.

#32 Feature/27 support root session
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Applications/Application.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Applications/ApplicationFactory.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Applications/ApplicationManager.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Applications/ApplicationStartup.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Applications/IWindowsApplication.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Applications/LocalApplicationFactory.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Applications/RemoteApplicationFactory.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Applications/WindowHandleApplicationFactory.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Aquality.WinAppDriver.xml
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Resources/Localization/be.json
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Resources/Localization/en.json
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Resources/Localization/ru.json
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Utilities/IProcessManager.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Utilities/IWinAppDriverLauncher.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Utilities/ProcessManager.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Utilities/WinAppDriverLauncher.cs
  Aquality.WinAppDriver/tests/Aquality.WinAppDriver.Tests/Applications/WindowHandleApplicationFactoryTests.cs
  Aquality.WinAppDriver/tests/Aquality.WinAppDriver.Tests/TestWithApplication.cs
  Aquality.WinAppDriver/tests/Aquality.WinAppDriver.Tests/Utilities/ProcessManagerTests.cs
Labels: Feature

#33 Extend Keyboard actions to be able to click named button several times
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Actions/ActionKey.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Actions/ApplicationActions.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Actions/IKeyboardActions.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Actions/KeyExtensions.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Actions/KeyboardActions.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Actions/ModifierKey.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Aquality.WinAppDriver.xml
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Elements/Actions/KeyboardActions.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Resources/Localization/be.json
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Resources/Localization/en.json
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Resources/Localization/ru.json
  Aquality.WinAppDriver/tests/Aquality.WinAppDriver.Tests/Actions/KeyboardActionsTests.cs
Labels: enhancement

#35 Feature/34 add properties for aquality services
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Applications/Application.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Applications/ApplicationFactory.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Applications/ApplicationStartup.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Applications/AqualityServices.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Applications/LocalApplicationFactory.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Applications/RemoteApplicationFactory.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Applications/WindowHandleApplicationFactory.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Aquality.WinAppDriver.csproj
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Aquality.WinAppDriver.xml
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Elements/Element.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Windows/Window.cs
  Aquality.WinAppDriver/tests/Aquality.WinAppDriver.Tests/Actions/KeyboardActionsTests.cs
  Aquality.WinAppDriver/tests/Aquality.WinAppDriver.Tests/Actions/MouseActionsTests.cs
  Aquality.WinAppDriver/tests/Aquality.WinAppDriver.Tests/Applications/ApplicationManagerTests.cs
  Aquality.WinAppDriver/tests/Aquality.WinAppDriver.Tests/Applications/AqualityServicesTests.cs
  Aquality.WinAppDriver/tests/Aquality.WinAppDriver.Tests/Applications/KeyboardActionsTests.cs
  Aquality.WinAppDriver/tests/Aquality.WinAppDriver.Tests/Applications/MouseActionsTests.cs
  Aquality.WinAppDriver/tests/Aquality.WinAppDriver.Tests/Applications/WindowHandleApplicationFactoryTests.cs
  Aquality.WinAppDriver/tests/Aquality.WinAppDriver.Tests/Elements/ElementFactoryTests.cs
  Aquality.WinAppDriver/tests/Aquality.WinAppDriver.Tests/Elements/ElementStateProviderTests.cs
  Aquality.WinAppDriver/tests/Aquality.WinAppDriver.Tests/Elements/ElementTests.cs
  Aquality.WinAppDriver/tests/Aquality.WinAppDriver.Tests/Localization/LocalizationFilesTest.cs
  Aquality.WinAppDriver/tests/Aquality.WinAppDriver.Tests/TestWithApplication.cs
  Aquality.WinAppDriver/tests/Aquality.WinAppDriver.Tests/Unit/Configuration/ConfigurationTests.cs
  Aquality.WinAppDriver/tests/Aquality.WinAppDriver.Tests/Utilities/ProcessManagerTests.cs
Labels: Feature

#37 Bug/22 fix send keys with key hold method
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Actions/ApplicationActions.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Actions/IKeyboardActions.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Actions/KeyboardActions.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Applications/LocalApplicationFactory.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Aquality.WinAppDriver.xml
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Elements/Actions/ElementActions.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Elements/Actions/KeyboardActions.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Elements/Actions/MouseActions.cs
  Aquality.WinAppDriver/src/Aquality.WinAppDriver/Elements/Element.cs
  Aquality.WinAppDriver/tests/Aquality.WinAppDriver.Tests/Actions/KeyboardActionsTests.cs
Labels: bug
